[/home/lopes_pc/Documents/docs_mestrado]
Sort=name;ascending;
ViewMode=icon
ShowHidden=false
SortOrder=ascending
SortColumn=name
SortFolderFirst=true
SortHiddenLast=false
SortCaseSensitive=true
Recursive=false
